Repository ir-engine/ir-engine-docs, pull requests merged in 2023-12, with the labels that each got.

#35 Adding no-spaces comment to engine installation docs
  docs/1_host/1_installation/readme.md
Labels: documentation

#36 Update to TS. Implement tsdoc route into build. Make action that will build deployment branch
  .gitignore
  docs/1_host/1_installation/3_windows.md
  docs/1_host/2_devops_deployment/0_microk8s_linux.md
  docs/1_host/2_devops_deployment/0_microk8s_windows.md
  docs/1_host/2_devops_deployment/1_docker_desktop.md
  docs/1_host/2_devops_deployment/1_minikube.md
  docs/1_host/2_devops_deployment/2_AWS_setup.md
  docs/1_host/2_devops_deployment/_accept_certificates.md
  docs/1_host/_category_.json
  docs/2_creator/4_development/5_behave_graph.md
  docs/2_creator/6_testing/5_debugging_device_wsl.md
  docs/2_creator/_category_.json
  docs/3_guest/_category_.json
  docusaurus.config.bak.js
  docusaurus.config.ts
  package.json
  sidebars.ts
  src/css/custom.css
  tsconfig.json
  typedoc.ts
Labels: verified-contributor

#38 reindex search after docs deployment
  .github/workflows/prepare-search.yml
  docusaurus.config.ts
Labels: verified-contributor

#40 [content] Cleanup of the `Developer Manual` section
  docs/03_manual/03_developer/01_projectsOverview.md
  docs/03_manual/03_developer/03_stateManagement.md
  docs/03_manual/03_developer/04_ecs.md
  docs/03_manual/03_developer/05_networking.md
  docs/03_manual/03_developer/06_actionsEventSourcing.md
  docs/03_manual/03_developer/07_testing/00_intro.md
  docs/03_manual/03_developer/07_testing/01_reasonableCode.md
  docs/03_manual/03_developer/07_testing/02_testDrivenDevelopment.md
  docs/03_manual/03_developer/07_testing/_category_.json
  docs/03_manual/03_developer/08_debugging/01_basic.md
  docs/03_manual/03_developer/08_debugging/02_deviceWSL.md
  docs/03_manual/03_developer/08_debugging/03_deployedInstanceServers.md
  docs/03_manual/03_developer/08_debugging/_category_.json
Labels: documentation, enhancement, verified-contributor

#39 [content] Cleanup of the `User`, `Overview`, `Contribute` and `Community` sections
  docs/00_overview/00_startHere.md
  docs/01_gettingStarted/00_intro.md
  docs/01_gettingStarted/01_guest.md
  docs/01_gettingStarted/02_creator.md
  docs/01_gettingStarted/03_developer.md
  docs/01_gettingStarted/04_host.md
  docs/03_manual/01_guest/00_intro.md
  docs/03_manual/01_guest/99_faq.md
  docs/03_manual/05_license.md
  docs/98_contributing/00_intro.md
  docs/99_community/00_intro.md
Labels: documentation, enhancement, verified-contributor

#41 Cleanup the `Creator Manual` section
  docs/03_manual/02_creator/00_intro.md
  docs/03_manual/02_creator/01_concepts/01_editorScenes.md
  docs/03_manual/02_creator/01_concepts/02_locations.md
  docs/03_manual/02_creator/02_studio/00_intro.md
  docs/03_manual/02_creator/02_studio/01_toolbar.md
  docs/03_manual/02_creator/02_studio/02_files.md
  docs/03_manual/02_creator/02_studio/03_preview.md
  docs/03_manual/02_creator/02_studio/04_viewport.md
  docs/03_manual/02_creator/02_studio/05_hierarchy.md
  docs/03_manual/02_creator/02_studio/06_properties.md
  docs/03_manual/02_creator/02_studio/07_assembly.md
  docs/03_manual/02_creator/02_studio/08_profile.md
  docs/03_manual/02_creator/02_studio/_category_.json
  docs/03_manual/02_creator/02_studio/_studio_overview.md
  docs/03_manual/02_creator/04_avatars/00_intro.md
  docs/03_manual/02_creator/04_avatars/_category_.json
  docs/03_manual/02_creator/05_project/00_intro.md
  docs/03_manual/02_creator/05_project/_category_.json
  docs/03_manual/02_creator/98_tutorials/02_unreal_bridge.md
  docs/03_manual/02_creator/99_faq.md
  docs/03_manual/03_developer/04_ecs.md
Labels: documentation, enhancement, verified-contributor

#44 Basic structure improvement for the `Behave Graph` article
  docs/01_gettingStarted/00_intro.md
  docs/01_gettingStarted/03_developer/00_intro.md
  docs/01_gettingStarted/03_developer/01_behaveGraph.md
  docs/01_gettingStarted/03_developer/02_typescript.md
  docs/01_gettingStarted/03_developer/_category_.json
  docs/03_manual/03_developer/02_behaveGraph.md
  docs/03_manual/03_developer/02_behaveGraph/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/02_concepts.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/01_types.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/02_entity/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/02_entity/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/03_component/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/03_component/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/04_state/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/04_state/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/05_events/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/05_events/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/06_actions/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/06_actions/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/07_custom/00_intro.md
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/07_custom/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/03_nodes/_category_.json
  docs/03_manual/03_developer/02_behaveGraph/04_usage.md
  docs/03_manual/03_developer/02_behaveGraph/05_config.md
  docs/03_manual/03_developer/02_behaveGraph/_category_.json
Labels: documentation, enhancement, verified-contributor

#89 [general + guest] Reorganize Guest + General sections
  docs/01_gettingStarted/01_guest.md
  docs/03_manual/01_general/00_intro.md
  docs/03_manual/01_general/01_concepts/02_instances.md
  docs/03_manual/01_general/01_concepts/_category_.json
  docs/03_manual/01_general/02_studio/00_intro.md
  docs/03_manual/01_general/02_studio/01_toolbar.md
  docs/03_manual/01_general/02_studio/02_files.md
  docs/03_manual/01_general/02_studio/03_preview.md
  docs/03_manual/01_general/02_studio/04_viewport.md
  docs/03_manual/01_general/02_studio/05_hierarchy.md
  docs/03_manual/01_general/02_studio/06_properties.md
  docs/03_manual/01_general/02_studio/07_assembly.md
  docs/03_manual/01_general/02_studio/08_profile.md
  docs/03_manual/01_general/02_studio/_category_.json
  docs/03_manual/01_general/02_studio/_studio_overview.md
  docs/03_manual/01_general/03_adminPanel/00_intro.md
  docs/03_manual/01_general/03_adminPanel/_category_.json
  docs/03_manual/01_general/98_glossary.md
  docs/03_manual/01_general/99_faq.md
  docs/03_manual/01_general/_category_.json
  docs/03_manual/01_guest/00_intro.md
  docs/03_manual/01_guest/_category_.json
  docs/03_manual/02_creator/02_studio/00_intro.md
  docs/03_manual/02_creator/03_assets/00_intro.md
  docs/03_manual/04_host/02_adminDashboard/_category_.json
Labels: documentation, verified-contributor, general

#96 typescript first pass
  docs/01_gettingStarted/03_developer/00_intro.md
  docs/01_gettingStarted/03_developer/02_typescript.md
Labels: verified-contributor

#95 doc: Delete CHANGELOG.md
  CHANGELOG.md
Labels: verified-contributor
