Repository ir-engine/ir-engine-docs, pull requests merged in 2024-05, with the labels that each got.

#176 [IR-2274] Landing Page: Simplify the components configuration
  src/pages/_colors.tsx
  src/pages/_landing/section/hero.tsx
  src/pages/_landing/section/personas.tsx
  src/pages/index.tsx
  src/pages/landing.tsx
  tailwind.config.ts
  website.config.ts
Labels: documentation, verified-contributor, general

#180 Replaced EE mentions across Developer docs and fixed typos related to TypeScript and VisualScript
  docs/developer/typescript/01_gettingStarted/01_quickstart.md
  docs/developer/typescript/01_gettingStarted/02_hello/01_ecs.md
  docs/developer/typescript/01_gettingStarted/02_hello/02_engine.md
  docs/developer/typescript/01_gettingStarted/02_hello/03_system.md
  docs/developer/typescript/01_gettingStarted/02_hello/04_component.md
  docs/developer/typescript/01_gettingStarted/02_hello/05_query.md
  docs/developer/typescript/01_gettingStarted/02_hello/90_congrats.md
  docs/developer/typescript/01_gettingStarted/02_hello/index.md
  docs/developer/typescript/02_basics/01_recap/01_styling.md
  docs/developer/typescript/02_basics/01_recap/03_query.md
  docs/developer/typescript/02_basics/01_recap/04_next.md
  docs/developer/typescript/02_basics/01_recap/index.md
  docs/developer/typescript/02_basics/03_state.md
  docs/developer/typescript/02_basics/05_project/index.md
  docs/developer/typescript/02_basics/50_debugging.md
  docs/developer/typescript/02_basics/50_locations.md
  docs/developer/typescript/02_basics/index.md
  docs/developer/typescript/04_state/50_state.md
  docs/developer/typescript/05_ecs/02_systems/50_order/index.md
  docs/developer/typescript/49_networking/_50_networking.md
  docs/developer/typescript/90_roadmap/index.md
  docs/developer/typescript/98_contributing/index.md
  docs/developer/typescript/typescript.md
  docs/developer/visualscript/01_gettingStarted/02_hello/index.md
  docs/developer/visualscript/01_gettingStarted/index.md
  docs/developer/visualscript/02_basics/70_project/index.md
  docs/developer/visualscript/02_basics/index.md
  docs/developer/visualscript/98_contributing/index.md
  docs/developer/visualscript/visualscript.md
Labels: documentation, verified-contributor

#179 Replacing instances of EE mentions in docs landing and the UI + Logo and favicon update
  static/img/favicon.ico
  static/img/logo.svg
  website.config.ts
Labels: documentation, verified-contributor

#178 Replacing the instances where Ethereal Engine is mentioned in the Manual
  docs/manual/01_install/01_linux.md
  docs/manual/01_install/03_windows.md
  docs/manual/01_install/03_windowsWSL.md
  docs/manual/01_install/04_controlCenter.md
  docs/manual/01_install/050_advanced/07_troubleshooting.md
  docs/manual/01_install/050_advanced/09_elasticKibana.md
  docs/manual/01_install/050_advanced/index.md
  docs/manual/02_concepts/01_projects.md
  docs/manual/02_concepts/03_locations.md
  docs/manual/02_concepts/index.md
  docs/manual/02_scene/01_studio/01_overview/08_profile.md
  docs/manual/02_scene/01_studio/01_overview/index.md
  docs/manual/02_scene/02_visualscript/index.md
  docs/manual/02_scene/05_management/index.md
  docs/manual/03_modules/01_engine/04_ecs.md
  docs/manual/03_modules/01_engine/05_networking.md
  docs/manual/03_modules/01_engine/08_debugging/index.md
  docs/manual/03_modules/03_world/03_assets/index.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/01_dashboard.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/02_servers.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/03_projects.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/05_locations.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/07_avatars.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/09_bots.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/10_channels.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/11_invites.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/12_recordings.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/13_resources.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/15_users.md
  docs/manual/03_modules/05_infrastructure/02_adminPanel/index.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/01_microk8s_linux.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/01_microk8s_windows.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/02_dockerDesktop.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/02_minikube.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/02_EKS.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/03_ECR.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/04_IAM.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/05_RDS.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/07_route53.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/08_agonesNginxRedis.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/13_fork.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/16_githubActions.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/index.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_installingProjects.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/04_databaseMigrations.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/05_setupGithubOAuth.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/07_releaseHelmChart.md
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/_acceptCertificates.md
  docs/manual/03_modules/05_infrastructure/98_tutorials/_category_.yml
  docs/manual/96_faq.md
  docs/manual/98_contributing/06_documentation/02_markdown.md
  docs/manual/98_contributing/index.md
  docs/manual/_partials/acceptCertificates.md
  docs/manual/_partials/controlCenter/step_configurations.md
  docs/manual/manual.md
Labels: documentation, verified-contributor

#177 Added documentation for new sub-route matching
  docs/manual/02_concepts/01_projects.md
Labels: verified-contributor

#175 Added guidelines for code formatting on save
  docs/manual/98_contributing/05_source/60_codeFormatting.md
  docs/manual/98_contributing/05_source/_category_.yml
  docs/manual/98_contributing/05_source/index.md
Labels: documentation, verified-contributor, developer
