Repository ir-engine/ir-engine-docs, pull requests merged in 2024-03, with the labels that each got.

#121 fix: Usability improvements to the contributing section
  .gitignore
  docs/manual/98_contributing/06_documentation/02_markdown.md
  docs/manual/98_contributing/06_documentation/03_structure.md
  readme.md
  src/pages/_landing/section/personas.tsx
Labels: documentation, verified-contributor, general

#117 [all] Move Advanced Setup out of modules/Infrastructure
  docs/manual/01_install/050_advanced/_category_.json
  docs/manual/01_install/_category_.json
  docs/manual/02_concepts/_category_.json
Labels: documentation, verified-contributor

#122 [developer] fix: typo errors
  docs/_partials/defaultProjects.md
  docs/developer/typescript/01_gettingStarted/02_hello/05_query.md
Labels: documentation, verified-contributor, developer

#124 [all] chg: Enable `/developer/typescript` cards on the simple landing page
  src/pages/_landing/section/hero.tsx
  src/pages/_landing/section/personas.tsx
Labels: documentation, verified-contributor, developer, general

#126 [all] chg: Add `hover` behavior to the custom mdx components
  src/components/TechnicalNote.tsx
  src/components/UnstyledDetails.tsx
Labels: documentation, verified-contributor, developer

#125 [all] new: Add `scroll-down` animated icon to the landing page
  src/pages/_landing/section/hero.tsx
  src/pages/_landing/section/personas.tsx
  static/img/expand.svg
Labels: documentation, verified-contributor, general

#128 Updated some documentation about GH Actions secrets
  docs/manual/03_modules/05_infrastructure/03_devopsDeployment/03_AWSSetup/13_fork.md
Labels: verified-contributor

#148 Update .vale.ini
  .vale.ini
Labels: verified-contributor

#153 [general] Write the introduction page of the General manual
  docs/manual/manual.md
Labels: verified-contributor
