Repository ir-engine/ir-engine-docs, pull requests merged in 2024-06, with the labels that each got.

#181 Revert "Added documentation for new sub-route matching"
  docs/manual/02_concepts/01_projects.md
Labels: verified-contributor

#162 Basic spatial module docs
  docs/manual/03_modules/02_spatial/01_transforms.md
  docs/manual/03_modules/02_spatial/02_spatialXRInput.md
  docs/manual/03_modules/02_spatial/03_objects.md
  docs/manual/03_modules/02_spatial/04_cameraSceneRendering.md
  docs/manual/03_modules/02_spatial/index.md
Labels: documentation, verified-contributor, developer

#163 Basic avatar concepts docs
  docs/manual/02_concepts/08_avatars/01_animations.md
  docs/manual/02_concepts/08_avatars/02_mocap.md
  docs/manual/02_concepts/08_avatars/03_IK.md
  docs/manual/02_concepts/08_avatars/04_avatarModels.md
  docs/manual/02_concepts/08_avatars/images/animation-export-presets.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack1.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack2.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack3.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack4.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack5.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack6.jpg
  docs/manual/02_concepts/08_avatars/images/animation-pack7.jpg
  docs/manual/02_concepts/08_avatars/images/force-vrm.jpg
  docs/manual/02_concepts/08_avatars/images/loop-animation.jpg
  docs/manual/02_concepts/08_avatars/images/to-vrm1.jpg
  docs/manual/02_concepts/08_avatars/images/to-vrm2.jpg
  docs/manual/02_concepts/08_avatars/images/to-vrm3.jpg
  docs/manual/02_concepts/08_avatars/images/upload-avatar1.jpg
  docs/manual/02_concepts/08_avatars/images/upload-avatar2.jpg
  docs/manual/02_concepts/08_avatars/images/upload-avatar3.jpg
  docs/manual/02_concepts/08_avatars/images/upload-avatar4.jpg
  docs/manual/03_modules/03_world/04_avatars/index.md
Labels: documentation, verified-contributor, creator
